---
output: github_document
---

# Margaux et les plantes invasives

## Projet

Projet de recherche sur l'impact des espèces exotiques envahissantes sur la croissance d'espèces indigènes de l'île de la Réunion.

## License

Open data (CC-BY 4.0 compatible with Etalab)

##  Direct link to download raw datasets

Work in progress

##  Thematic scope (All biodiversity including paleo- and archaeo-biodiversity)

Espèces de plantes de l'île de la Réunion.

##  Geographic scope (Data produced by France)

Île de la Réunion
  
## Temporal coverage (at least one data acquisition date)

Work in progress

## Abstract

## Title, authors and contacts

Margaux Rojat

## Acquisition framework (at least via a text field)



## DOI / unique identifiers

##    taxonomic coverage (if taxa are present)

Plante vasculaire de l'Ile de la Réunion

##    keywords related to the Thesaurus

##    Data attributes (Dictionary of data attributes with units and descriptions)

```{r echo=FALSE}
data_attributes <- data.table::fread("data_attributes.csv", encoding = "Latin-1")
data_attributes <- data_attributes[1:25,]

knitr::kable(data_attributes)
```

##    Semantic annotation (Keywords and attribute names, unlimited usable resources)


